# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A jekyll test site for GitHub Pages
email: new-blog-test-5@lamurakami.com
description: > # this means to ignore newlines until "baseurl:"
  This site is one of many static sites created by LAMurakami to explore
  Jekyll, Liquid, git, GitHub, GitHub Pages, Custom domains, HTTPS,
  Let’s Encrypt, DNS, DDNS, HTTP and HTTP redirects and more.
baseurl: "/new-blog-test-6" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
# url: "http://new-blog-test-6.lamurakami.com" # the base hostname & protocol for your site
github_username: LAMurakami

# Build settings
markdown: kramdown
